sudo: required 
services:
        - docker

before_install:
        - docker build -t kumawat8560/docker-react -f Dockerfile.dev .

script:
        - docker run kumawat8560/docker-react npm run test -- --coverage

deploy:
        provider: elasticbeanstalk
        region: "ap-south-1"
        app: docker
        env: "Docker-env"
        bucket_name: "elasticbeanstalk-ap-south-1-485961692390"
        bucket_path: "docker"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY" 
