sudo: required 
services:
        - docker

before_install:
        - docker build -t kumawat8560/docker-react -f Dockerfile.dev .

scripts:
        - docker run kumawat8560/docker-react npm run test -- --coverage 
